### ISSUE TITLE
https

### ISSUE THREAD

**Issue by Craytor** [giannoug/facebook-messenger-bot#1]
Isn't this required to have https in order to use it as a web hook?

**Comment by giannoug** [comment]
Yes, https is required. Furthermore you shouldn't use a self-signed certificate, Facebook doesn't like those. You can either use your own web server, provided that you have a certificate or just use Heroku (or your favorite app engine that serves over https).

If you use nginx, you can use the following simple rule to proxy everything sent to `/` to your bot.

```
location / {
    proxy_pass http://127.0.0.1:1337;
    proxy_redirect off;
}
```
