### ISSUE TITLE
Use fb-messenger?

### ISSUE THREAD

**Issue by DiegoRBaquero** [giannoug/facebook-messenger-bot#2]
Hi there! I found this cool project and wanted to share mine, maybe you find it useful and use it as a module in yours :)

Link: https://github.com/DiegoRBaquero/node-fb-messenger 
NPM module: https://www.npmjs.com/package/fb-messenger

Thank you for your time :)

**Comment by giannoug** [comment]
Nice one Diego! I'll try to keep this repo barebones and as close to the Facebook Getting Started guide as possible, but I'll surely use your module in a future project.

Thanks for your time!
